#!/bin/bash

# Copyright © 2024 slashOS Team and Contributors

### ΤΟ DO ###
# - Manage flatpak
# - Manage snap
# - Manage npm
# - Manage pip (already implemented but not documented or advertised)
# - Updating/Downgrading specific packages
# - Updating AUR and pip packages
# - Searching in all package managers/formats spm wraps around
# - Config file (when needed, not big priority rn)
# - Integration with GNOME Software or creation of a completely new graphical frontend.

help(){
  echo "Welcome to the Slash Package Manager!"
  echo "This is a very early alpha and is only intended to be used on Arch-Linux based systems."
  echo ""
  echo "Syntax: spm [action] ([arguements] [package])"
  echo ""
  echo "Main Actions:"
  echo "        help        | shows this, don't specify a package after"
  echo "        remove      | removes a package specified using pacman"
  echo "        install     | installs the specified package using pacman" 
  echo "                    | (use the -a arguement to install from the AUR instead)"
  echo "        update      | updates all packages (use -a to update AUR only or -ap to update both pacman and" 
  echo "                    | AUR packages)."
  echo ""
  echo "NOTE: Experiemental options are not shown here!"
  exit 0
}

remove() {
    sudo pacman -R $1
    echo "Completed!"    
}

pipremove() {
    pip uninstall $1 --break-system-packages
    exit 0
}

install() {
    sudo pacman -Sy $1
    exit 0
}

aurinstall() {
    echo "Preparing to install $1"
    cd /home/$USER
    mkdir aurinstallTEMP
    cd aurinstallTEMP
    curl https://aur.archlinux.org/cgit/aur.git/snapshot/$1.tar.gz --output $1.tar.gz
    tar -xvzf $1.tar.gz
    cd $1
    makepkg --install --syncdeps --clean --noconfirm
    if [ $? -eq 0 ]; 
    then
      echo "$1 was installed successfully."
      echo "Adding $1 to spm AUR package history..."
      sudo echo "$1" >> /etc/spmaurhistory
    else
      echo "(spm) Error: Installing $1 failed."
      exit 1
    fi

    echo "Removing left over junk files."
    cd /home/$USER
    sudo rm -rf aurinstallTEMP
}

pipinstall() {
    echo "Preparing to install $1"
    pip install $1 --break-system-packages
    exit 0
}

update() { 
   echo "Updating pacman packages..." 
   sudo pacman -Syu
   exit 0
}

if [ "$1" == "help" ] && [ "$#" -eq  1 ]
then
  help
elif [ "$1" == "install" ] && [ "$#" -eq  2 ]
then
  install "$2"
elif [ "$1" == "install" ] && [ "$2" == "-p" ] && [ "$#" -eq  3 ]
then
  pipinstall "$3"
elif [ "$1" == "install" ] && [ "$2" == "-a" ] && [ "$#" -eq  3 ]
then
  aurinstall "$3"
elif [ "$1" == "remove" ] && [ "$#" -eq  2 ]
then
  remove "$2"
elif [ "$1" == "remove" ] && [ "$2" == "-p" ] && [ "$#" -eq  3 ]
then
  pipremove "$3"
elif [ "$1" == "update" ] && [ "$#" -eq  1 ]
then
  update
else
  echo "(spm) Error: Invalid Syntax"
  exit 1 
fi
